dist: xenial
language: python
python:
  - "3.6"
  - "3.7"
install:
  - pip install pipenv
  - pipenv install --dev
script:
  - pytest
deploy:
  provider: pypi
  user: paulbailey
  password:
  on:
    tags: true
  distributions: "sdist bdist_wheel"
  skip_existing: true
