dist: xenial
language: python
python:
- '3.7'
install:
- pipenv install --dev
- pipenv install
script:
- pytest
deploy:
  - provider: pypi
    user: paulbailey
    password:
      secure: jLrBn0CzIUDbNl6M11XFRaQzbzCFS88eseTDdlE7Oh36EBcnXMJdbv5n4ZU20GP9/VZTK5d55WQgiaqNcbfnMt1TpEUGvYr8M7ffR4E0KMMhOXclUeoRaaNKGW/l69SZr0yuLCXIhA8ZXppspssiSwO7n24TPmvH7P/QP139gonHOUQsbysZNIlBhSpw/esMJugIvpAvBt652vqIV/W9g0AdEN3UZWfgdyNygOBndCvdH5Ha7+g8HOBv6jkX9WWCW+ajRCLpNBBHydGysdQMFE+KzcxXOC3dmzEkHL6KEaxPpqVUjlJ+eBxTqDwLqKTg2/ZGKE4SLztAGtxTXxiEfopkf06abqlUhjnOM+ie9SlUc3kySeZbQOhDx4y0KeZqxhzkjcaqQINf2Y7wxPvMFeope5QHjmA/Y6KGSqo5VpEExs0XK8mX2rhUypnWmhURJLvVA/ed4VVWiJ415OkHFIw1yhTC2EzZiR+Kb1Qna8/8ISQBONT7+BM685jXQAf7pd8xny5iKBLSqJ/KNI7yy4kA87l5qWdk6F24ZXPKCd/A+NVMETbLrRgJJIpHoOKLqqP76co9ywcQU6FCtM4pxr3BGK/ZnWC9vmrVV6JDu1vCM/ZYfIw697cQzGVEI0OP5U3uV0BcO4Ab+UU+1aaHnpNnMYD9K5xboK5A1C+WDkY=
    on:
      tags: true
    distributions: sdist bdist_wheel
    skip_existing: true
